FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y python3-pip python3-dev

RUN apt-get install -y wget
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update
RUN apt-get install -y google-chrome-stable
RUN apt-get clean
RUN python3 -m pip install --upgrade pip 
# RUN 
ENV PYTHONBUFFERED 1
ENV DJANGO_SETTINGS_MODULE=search_project.settings.prod

WORKDIR /
RUN pip3 install -r requirements.txt
ADD secrets.json /
ADD django-bootstrap-modal-forms-2.2.0 /
COPY . /

RUN cd /django-bootstrap-modal-forms-2.2.0/
RUN python /django-bootstrap-modal-forms-2.2.0/setup.py install
RUN cd ..
CMD ["gunicorn", "search_project.wsgi:application", "--bind", "0.0.0.0:8000"]
# CMD ["python", "manage.py", "runserver"]
EXPOSE 8000

