# Generated by Django 3.2.3 on 2021-07-13 14:54

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import search_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrwalingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enter_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-created_at', 'enter_name'],
            },
        ),
        migrations.CreateModel(
            name='EnterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyEnterPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, upload_to='search_job/%Y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaraminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=1000)),
                ('url', models.SlugField(blank=True, max_length=1000)),
                ('upload_to_path', models.CharField(blank=True, max_length=2000)),
                ('enter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='search_app.crwalingmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=300)),
                ('photo', models.ImageField(blank=True, upload_to='search_app/%Y/%m/%d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyEnterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('link', models.SlugField(blank=True, max_length=1000)),
                ('memo', models.TextField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search_app.myenterphoto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='myenterphoto',
            name='my_enter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_app.myenterprise'),
        ),
        migrations.CreateModel(
            name='KreditJobInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=1000)),
                ('url', models.SlugField(blank=True, max_length=1000)),
                ('upload_to_path', models.CharField(blank=True, max_length=2000)),
                ('jobdom_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), default=list, size=None)),
                ('enter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='search_app.crwalingmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobPlanetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=1000)),
                ('url', models.SlugField(blank=True, max_length=1000)),
                ('upload_to_path', models.CharField(blank=True, max_length=2000)),
                ('enter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='search_app.crwalingmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobKoreaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=1000)),
                ('url', models.SlugField(blank=True, max_length=1000)),
                ('upload_to_path', models.CharField(blank=True, max_length=2000)),
                ('enter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='search_app.crwalingmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnterUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(max_length=1000)),
                ('enter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_app.enterinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EnterInfoPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('enter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_app.enterinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CrwalingPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(max_length=1000, upload_to=search_app.models.crwaling_photo_path)),
                ('jobkorea_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search_app.jobkoreainfo')),
                ('jobplanet_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search_app.jobplanetinfo')),
                ('kreditjob_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search_app.kreditjobinfo')),
                ('saramin_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search_app.saramininfo')),
            ],
            options={
                'ordering': ['-created_at', 'saramin_info', 'jobkorea_info', 'jobplanet_info', 'kreditjob_info'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=90)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_app.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
