# Generated by Django 3.2.3 on 2021-06-29 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_alter_post_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, upload_to='search_job/%Y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyEnterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('memo', models.TextField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_app.enterphoto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='enterphoto',
            name='enter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_app.myenterprise'),
        ),
    ]
