# Generated by Django 3.2.3 on 2021-07-01 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search_app', '0003_auto_20210629_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myenterprise',
            name='photo',
        ),
        migrations.AddField(
            model_name='myenterprise',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myenterprise',
            name='company',
            field=models.CharField(default='company', max_length=100),
            preserve_default=False,
        ),
    ]
