version: "3.8"
services:
    nginx:
        image: nginx
        container_name : nginx_service
        build:
            context: .
            dockerfile: ./etc/nginx/Dockerfile
        volumes:
            - ./:/project3/etc/nginx/nginx.conf
        ports:
            - "80:80"
        depends_on:
            - project3
    project3:
        image: skarndrkd/project3:1.2
        build:
            context: .
            dockerfile: ./Dockerfile
        working_dir: /project3
        volumes:
            - ./:/project3
        ports:
            - "8000:8000"
        extra_hosts: 
            - host.docker.internal:host-gateway
        # command: bash -c "pip3 install -r requirements.txt && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
        command: bash -c "pip3 install -r /requirements.txt && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py crontab remove && python3 manage.py crontab add && python3 manage.py crontab show && service cron start && gunicorn search_project.wsgi:application --bind 0.0.0.0:8000"
    celery:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/project3
        depends_on:
            - project3
        command: celery -A search_project worker -Q crwaling_enter_info -l info --concurrency=1
        # command: celery -A search_project worker -l info
    flower:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/project3
        depends_on: 
            - project3
            - celery
        environment: 
            - CELERY_BROKER_URL=redis://redis.4whnmi.ng.0001.apn2.cache.amazonaws.com:6379/0
            - FLOWER_PORT=5555
        ports:
            - "5555:5555"
        command: celery -A search_project flower --broker_api=redis://redis.4whnmi.ng.0001.apn2.cache.amazonaws.com:6379/0
volumes: 
    project3: